version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/usr/src/app
    links:
      - mysql
