apiVersion: v1
kind: Service
metadata:
  labels:
    name: sprintfy-mysql
  name: sprintfy-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: sprintfy-mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sprintfy-mysql-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sprintfy-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sprintfy-mysql
    spec:
      containers:
      - name: sprintfy-mysql
        image: mysql:latest
        args:
          - "--ignore-db-dir"
          - "lost+found"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: '1'
        volumeMounts:
          - name: sprintfy-mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: sprintfy-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: sprintfy-mysql-claim
