apiVersion: v1
kind: Service
metadata:
  labels:
    name: sprintfy-mysql
  name: sprintfy-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: sprintfy-mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sprintfy-mysql
spec:
  serviceName: sprintfy-mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: sprintfy-mysql
    spec:
      containers:
      - name: sprintfy-mysql
        image: mysql:latest
        resources:
          requests:
            cpu: "5m"
        args:
          - "--ignore-db-dir"
          - "lost+found"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: '1'
        volumeMounts:
          - name: sprintfy-mysql-persistent-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: sprintfy-mysql-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
